### ISSUE TITLE
(question) the 'bytes' array is already in bigendian/network byte order ?

### ISSUE THREAD

**Issue by danieagle** [JaegerMa/ipaddr#1]
Hi! Very Very Very Thanks for creating this library!

The address.bytes[] are already in network byte order (Bigendian) ?

Very Very Very Thanks in Advance!
Best Wishes,
GrateFull, Dani.

**Comment by JaegerMa** [comment]
Hi. Yes, the bytes array in V4Address and V6Address is in BigEndian, meaning the first byte contains the most significant bits.

**Comment by danieagle** [comment]
Yahoo!!!
Very Very Very Thanks!!!

Best Wishes,
GrateFull, Dani.
